
#ifndef _COMMON_H_
#define _COMMON_H_	

#include"phy_api.h"

static const value_string tagType_phy[] = 
{
    {PHY_PARAM_REQUEST ,"PHY_PARAM_REQUEST"},
    {PHY_PARAM_RESPONSE ,"PHY_PARAM_RESPONSE"},            
    {PHY_CELL_CONFIG_REQUEST ,"PHY_CELL_CONFIG_REQUEST"},        
    {PHY_CELL_CONFIG_RESPONSE ,"PHY_CELL_CONFIG_RESPONSE"},       
    {PHY_START_REQUEST ,"PHY_START_REQUEST"},
    {PHY_STOP_REQUEST ,"PHY_STOP_REQUEST"},               
    {PHY_STOP_INDICATION ,"PHY_STOP_INDICATION"},            
    {PHY_UE_CONFIG_REQUEST ,"PHY_UE_CONFIG_REQUEST"},          
    {PHY_UE_CONFIG_RESPONSE ,"PHY_UE_CONFIG_RESPONSE"},         
    {PHY_ERROR_INDICATION ,"PHY_ERROR_INDICATION"},           
    {PHY_DL_CONFIG_REQUEST ,"PHY_DL_CONFIG_REQUEST"},
    {PHY_UL_CONFIG_REQUEST ,"PHY_UL_CONFIG_REQUEST"},
    {PHY_UL_SUBFRAME_INDICATION ,"PHY_UL_SUBFRAME_INDICATION"},     
    {PHY_DL_HI_DCI0_REQUEST ,"PHY_UL_HI_DCI0_REQUEST"},         
    {PHY_DL_TX_REQUEST ,"PHY_DL_TX_REQUEST"},              
    {PHY_UL_HARQ_INDICATION ,"PHY_UL_HARQ_INDICATION"},         
    {PHY_UL_CRC_INDICATION ,"PHY_UL_CRC_INDICATION"},          
    {PHY_UL_RX_ULSCH_INDICATION ,"PHY_UL_RX_ULSCH_INDICATION"},     
    {PHY_UL_RACH_INDICATION ,"PHY_UL_RACH_INDICATION"},         
    {PHY_UL_SRS_INDICATION ,"PHY_UL_SRS_INDICATION"},          
    {PHY_UL_RX_SR_INDICATION ,"PHY_UL_RX_SR_INDICATION"},        
    {PHY_UL_RX_CQI_INDICATION ,"PHY_UL_RX_CQI_INDICATION"}      
}; 

#endif
